config/routes.rb
IdeaCatalog::Application.routes.draw do
  get "welcome/index"

  get 'tags/:tag', to: 'ideas#index', as: :tag
  resources :ideas

   root :to => 'welcome#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :background, :description, :titel, :tag_list
  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    if params[:tag]
    @ideas = Idea.tagged_with(params[:tag])
  else
    @ideas = Idea.all
  end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titel %><br />
    <%= f.text_field :titel %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :background %><br />
    <%= f.text_area :background %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags komma adskildte"%><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Ideer</h1>
<p class="alert alert-info"><strong>Bemærk!</strong> Kategorien "alle" er ideer som er tiltænkt alle. Det er ikke en mulighed for at vælge alle ideer!<br/>
Du kan vælge alle ideer i menuen i toppen.<br/>
Kategorierne har skrift-størrelse efter hvor mange ideer de indeholder.
</p>
<div id="tag_cloud">
<h2>Kategorier</h2>
  <% tag_cloud Idea.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <br/>
  <% end %>
</div>
<hr>
<p class="well">
Nedenfor er listen af ideer, klik på titlen for at læse mere
<table class="table table-hover">
  <tr>
    <th>Titel</th>
    
    <th>kategori</th>
    <th hidden></th>

    <th hidden></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><strong><%= link_to idea.titel, idea %></strong></td>
   
    <td>
      <%= raw idea.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    </td>
    
    <td hidden><%= link_to 'Redigér', edit_idea_path(idea) %></td>
    <td hidden><%= link_to 'Slet', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</p>
<br />

<%= link_to 'Ny ide', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titel:</b>
  <%= @idea.titel %>
</p>

<p>
  <b>Beskrivelse:</b>
  <%= @idea.description %>
</p>

<p>
  <b>Baggrund:</b>
  <%= @idea.background %>
</p>


<%= link_to 'Redigér', edit_idea_path(@idea) %> |
<%= link_to 'Tilbage', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mig - Møde - Missionshus</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
 <header class="navbar navbar-inverse navbar-fixed-top" id="main-navbar">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Mig - Møde - Missionshus</a>
          
        </div>
        <ul class="nav navbar-nav">
            <li><a href="/">Hjem</a></li>
           <li><%= link_to 'Alle ideer', ideas_path %></li>
          </ul>
    
      </div>
    </header>

  <div class="container">
    <div class="starter-template">
      <div class="span9"><%= yield %></div>
      
    </div>
  </div>
  <footer id="footer">
      <div class="container">
        <p class="text-muted credit">Lavet af <a href="http://hebsgaard.dk">khebbie</a></a>.</p>
      </div>
    </footer>
    <script type="text/javascript">
$(window).resize(function () { 
   $('body').css('padding-top', parseInt($('#main-navbar').css("height"))+10);
});

$(window).load(function () { 
   $('body').css('padding-top', parseInt($('#main-navbar').css("height"))+10);         
}); 
    </script>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Mig - Møde - Missionshus</h1>
<p class="lead">
	Denne hjemmeside er et referat af mødet i Stjær Galten missionshus d. 25. november 2012 - mødet havde titlen "Mig - Møde - Missionhus"<br/>
	Der kom mange ideer frem på mødet - som forsøges fremstillet på denne hjemmeside<br/>
	Jeg har forsøgt at fordele ideerne på de teams som har ansvaret for dem, det har jeg kaldt "kategorier"<br/>
	Nedenfor kan du se de forskellige kategorier, hvis du klikker på dem, vil du se ideer for de specifikke områder<br/>
	Vil du se alle ideer skal du klikke i menuen foroven

</p>
<div id="tag_cloud">
<h2>Kategorier</h2>
  <% tag_cloud Idea.tag_counts, %w[s m l] do |tag, css_class| %>
 
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <br/>
  <% end %>
  <br/>
  <%= link_to 'Alle ideer', ideas_path, :class => "btn btn-primary" %>
<br/>
<hr>
  <img src="assets/bethesda.jpg"/>
  
</div>
<div class="span3">
        <h2>Om Mig - Møde - Missionshus</h2>
       Jeg har forsøgt at fordele relevant output på dem som bør tage ansvar for det, men andre er naturligvis velkomne til at tage ansvar for vores alle sammens fællesskab
      </div>